-- MySQL Script generated by MySQL Workbench
-- Sun Aug 29 15:09:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imobiliaria` DEFAULT CHARACTER SET utf8 ;
USE `imobiliaria` ;

-- -----------------------------------------------------
-- Table `imobiliaria`.`casaApartamentoPossui`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`casaApartamentoPossui` (
  `idCasaApartPossui` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qtdQuartos` INT NULL,
  `qtdSuites` INT NULL,
  `qtdSalasEstar` INT NULL,
  `qtdSalasJantar` INT NULL,
  `numVagasGaragem` INT NULL,
  `area` DECIMAL NULL,
  `possuiArmarioEmb` TINYINT NULL,
  `descricao` VARCHAR(300) NULL,
  PRIMARY KEY (`idCasaApartPossui`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`casa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`casa` (
  `idCasa` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `casaApartPossui_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCasa`),
  INDEX `fk_casa_casaApartamentoPossui_idx` (`casaApartPossui_id` ASC),
  CONSTRAINT `fk_casa_casaApartamentoPossui`
    FOREIGN KEY (`casaApartPossui_id`)
    REFERENCES `imobiliaria`.`casaApartamentoPossui` (`idCasaApartPossui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`apartamento` (
  `idApart` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `andarApart` INT NULL,
  `valorCondApart` DECIMAL NULL,
  `possuiPort24` TINYINT NULL,
  `casaApartPossui_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idApart`),
  INDEX `fk_apartamento_casaApartamentoPossui1_idx` (`casaApartPossui_id` ASC),
  CONSTRAINT `fk_apartamento_casaApartamentoPossui1`
    FOREIGN KEY (`casaApartPossui_id`)
    REFERENCES `imobiliaria`.`casaApartamentoPossui` (`idCasaApartPossui`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`terreno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`terreno` (
  `idTerrno` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `areaTerreno` DECIMAL NULL,
  `largura` DECIMAL NULL,
  `comprimento` DECIMAL NULL,
  `possuiAcliveDeclive` TINYINT NULL,
  PRIMARY KEY (`idTerrno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`salaComercial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`salaComercial` (
  `idSalaComercial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `areaSalaCom` DECIMAL NULL,
  `qtdBanheiros` INT NULL,
  `qtdComodos` INT NULL,
  PRIMARY KEY (`idSalaComercial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`dadosClientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`dadosClientes` (
  `cpfCliente` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `endereco` VARCHAR(300) NULL,
  `email` VARCHAR(60) NULL,
  `sexo` CHAR(1) NOT NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `profissao` VARCHAR(150) NULL,
  PRIMARY KEY (`cpfCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`clienteProprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`clienteProprietario` (
  `cpfCliProp` VARCHAR(11) NOT NULL,
  `dadosCli_cpfCli` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cpfCliProp`),
  INDEX `fk_clienteProprietario_dadosClientes1_idx` (`dadosCli_cpfCli` ASC),
  CONSTRAINT `fk_clienteProprietario_dadosClientes1`
    FOREIGN KEY (`dadosCli_cpfCli`)
    REFERENCES `imobiliaria`.`dadosClientes` (`cpfCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`clienteUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`clienteUsuario` (
  `cpfCliUsuario` VARCHAR(11) NOT NULL,
  `dadosCli_cpfCli` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cpfCliUsuario`),
  INDEX `fk_clienteUsuario_dadosClientes1_idx` (`dadosCli_cpfCli` ASC),
  CONSTRAINT `fk_clienteUsuario_dadosClientes1`
    FOREIGN KEY (`dadosCli_cpfCli`)
    REFERENCES `imobiliaria`.`dadosClientes` (`cpfCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`contato` (
  `idContato` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeContato` VARCHAR(150) NOT NULL,
  `telefoneContato` VARCHAR(11) NOT NULL,
  `dadosCli_cpfCli` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idContato`),
  INDEX `fk_contato_dadosClientes1_idx` (`dadosCli_cpfCli` ASC),
  CONSTRAINT `fk_contato_dadosClientes1`
    FOREIGN KEY (`dadosCli_cpfCli`)
    REFERENCES `imobiliaria`.`dadosClientes` (`cpfCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`cargo` (
  `idCargo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeCargo` VARCHAR(45) NOT NULL,
  `salarioBase` DECIMAL NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`funcionario` (
  `cpfFunc` VARCHAR(11) NOT NULL,
  `nomeFunc` VARCHAR(150) NOT NULL,
  `telefFunc` VARCHAR(10) NULL,
  `enderecoFunc` VARCHAR(300) NULL,
  `telefContatoFunc` VARCHAR(11) NULL,
  `celularFunc` VARCHAR(11) NULL,
  `dataIngressoFunc` DATE NOT NULL,
  `cargo_id` INT UNSIGNED NOT NULL,
  `usuario` VARCHAR(60) NULL,
  `senha` VARCHAR(300) NULL,
  PRIMARY KEY (`cpfFunc`),
  INDEX `fk_funcionario_cargo1_idx` (`cargo_id` ASC),
  CONSTRAINT `fk_funcionario_cargo1`
    FOREIGN KEY (`cargo_id`)
    REFERENCES `imobiliaria`.`cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovel` (
  `idImovel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `terreno_id` INT UNSIGNED NULL,
  `salaComercial_id` INT UNSIGNED NULL,
  `casa_id` INT UNSIGNED NULL,
  `apartamento_id` INT UNSIGNED NULL,
  `tipoDisponibilidade` VARCHAR(45) NOT NULL,
  `sitDispImovel` VARCHAR(45) NULL,
  `dataConst` DATE NULL,
  `enderecoImovel` VARCHAR(160) NULL,
  `bairroImovel` VARCHAR(160) NOT NULL,
  `valor` DECIMAL NULL,
  `valorReal` DECIMAL NULL,
  `valorImobiliaria` DECIMAL NULL,
  `clienteUsuario_cpf` VARCHAR(11) NULL,
  `dataDispVendaLocacao` DATE NULL,
  `dataVendidoAlugado` DATE NULL,
  `dispVendaLocacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idImovel`),
  INDEX `fk_imovel_terreno1_idx` (`terreno_id` ASC),
  INDEX `fk_imovel_salaComercial1_idx` (`salaComercial_id` ASC),
  INDEX `fk_imovel_casa1_idx` (`casa_id` ASC),
  INDEX `fk_imovel_apartamento1_idx` (`apartamento_id` ASC),
  INDEX `fk_imovel_clienteUsuario1_idx` (`clienteUsuario_cpf` ASC),
  CONSTRAINT `fk_imovel_terreno1`
    FOREIGN KEY (`terreno_id`)
    REFERENCES `imobiliaria`.`terreno` (`idTerrno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_salaComercial1`
    FOREIGN KEY (`salaComercial_id`)
    REFERENCES `imobiliaria`.`salaComercial` (`idSalaComercial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_casa1`
    FOREIGN KEY (`casa_id`)
    REFERENCES `imobiliaria`.`casa` (`idCasa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_apartamento1`
    FOREIGN KEY (`apartamento_id`)
    REFERENCES `imobiliaria`.`apartamento` (`idApart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_clienteUsuario1`
    FOREIGN KEY (`clienteUsuario_cpf`)
    REFERENCES `imobiliaria`.`clienteUsuario` (`cpfCliUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`fotos` (
  `idFoto` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomeArq` VARCHAR(200) NOT NULL,
  `imovel_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idFoto`),
  INDEX `fk_fotos_imovel1_idx` (`imovel_id` ASC),
  CONSTRAINT `fk_fotos_imovel1`
    FOREIGN KEY (`imovel_id`)
    REFERENCES `imobiliaria`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`imovelClienteProprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`imovelClienteProprietario` (
  `imovel_id` INT UNSIGNED NOT NULL,
  `cpfClienteProp` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`imovel_id`, `cpfClienteProp`),
  INDEX `fk_imovel_has_clienteProprietario_clienteProprietario1_idx` (`cpfClienteProp` ASC),
  INDEX `fk_imovel_has_clienteProprietario_imovel1_idx` (`imovel_id` ASC),
  CONSTRAINT `fk_imovel_has_clienteProprietario_imovel1`
    FOREIGN KEY (`imovel_id`)
    REFERENCES `imobiliaria`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_imovel_has_clienteProprietario_clienteProprietario1`
    FOREIGN KEY (`cpfClienteProp`)
    REFERENCES `imobiliaria`.`clienteProprietario` (`cpfCliProp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`fiador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`fiador` (
  `cpfFiador` VARCHAR(11) NOT NULL,
  `nomeFiador` VARCHAR(160) NOT NULL,
  `telefoneFiador` VARCHAR(11) NOT NULL,
  `imovel_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cpfFiador`),
  INDEX `fk_fiador_imovel1_idx` (`imovel_id` ASC),
  CONSTRAINT `fk_fiador_imovel1`
    FOREIGN KEY (`imovel_id`)
    REFERENCES `imobiliaria`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`indicados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`indicados` (
  `cpfIndicado` VARCHAR(11) NOT NULL,
  `nomeIndicado` VARCHAR(160) NOT NULL,
  `telefoneIndicado` VARCHAR(11) NOT NULL,
  `imovel_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cpfIndicado`),
  INDEX `fk_indicados_imovel1_idx` (`imovel_id` ASC),
  CONSTRAINT `fk_indicados_imovel1`
    FOREIGN KEY (`imovel_id`)
    REFERENCES `imobiliaria`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`formaPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`formaPagamento` (
  `idFormPag` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descFormPag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFormPag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`transacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`transacao` (
  `idTransacao` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `dataTransacao` DATE NOT NULL,
  `imovel_id` INT UNSIGNED NOT NULL,
  `func_cpf` VARCHAR(11) NOT NULL,
  `cliUsuario_cpf` VARCHAR(11) NOT NULL,
  `numContrato` INT NOT NULL,
  `formPag_id` INT UNSIGNED NOT NULL,
  `valorComisFunc` DECIMAL NULL,
  PRIMARY KEY (`idTransacao`),
  INDEX `fk_transacao_imovel1_idx` (`imovel_id` ASC),
  INDEX `fk_transacao_funcionario1_idx` (`func_cpf` ASC),
  INDEX `fk_transacao_clienteUsuario1_idx` (`cliUsuario_cpf` ASC),
  INDEX `fk_transacao_formaPagamento1_idx` (`formPag_id` ASC),
  CONSTRAINT `fk_transacao_imovel1`
    FOREIGN KEY (`imovel_id`)
    REFERENCES `imobiliaria`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_funcionario1`
    FOREIGN KEY (`func_cpf`)
    REFERENCES `imobiliaria`.`funcionario` (`cpfFunc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_clienteUsuario1`
    FOREIGN KEY (`cliUsuario_cpf`)
    REFERENCES `imobiliaria`.`clienteUsuario` (`cpfCliUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacao_formaPagamento1`
    FOREIGN KEY (`formPag_id`)
    REFERENCES `imobiliaria`.`formaPagamento` (`idFormPag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`salario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`salario` (
  `idSalario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `salario` DECIMAL NOT NULL,
  `func_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idSalario`),
  INDEX `fk_salario_funcionario1_idx` (`func_cpf` ASC),
  CONSTRAINT `fk_salario_funcionario1`
    FOREIGN KEY (`func_cpf`)
    REFERENCES `imobiliaria`.`funcionario` (`cpfFunc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imobiliaria`.`historicoImovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imobiliaria`.`historicoImovel` (
  `idHistImov` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `infoAntImovel` TEXT(1024) NOT NULL,
  `imovel_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idHistImov`),
  INDEX `fk_historicoImovel_imovel1_idx` (`imovel_id` ASC),
  CONSTRAINT `fk_historicoImovel_imovel1`
    FOREIGN KEY (`imovel_id`)
    REFERENCES `imobiliaria`.`imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
